const assert = require('node:assert/strict');
const { execFileSync } = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { afterEach, test } = require('node:test');

const { readVersionSource, releaseMetadata, syncVersion } = require('../sync-version');

const temporaryRoots = [];

function fixture({
  versions = { fnos: '1.2.3', macos: '2.3.4', windows: '3.4.5' },
  manifestVersion = versions.fnos,
  xcodeVersion = versions.macos,
  windowsCargoVersion = versions.windows,
  windowsCargoLockVersion = windowsCargoVersion,
  tauriVersion = versions.windows,
} = {}) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'flux-reader-version-test-'));
  temporaryRoots.push(root);
  fs.mkdirSync(path.join(root, 'versions'), { recursive: true });
  fs.mkdirSync(path.join(root, 'apps', 'fnos', 'package'), { recursive: true });
  fs.mkdirSync(path.join(root, 'apps', 'macos', 'FluxReader.xcodeproj'), { recursive: true });
  fs.mkdirSync(path.join(root, 'apps', 'windows', 'src-tauri'), { recursive: true });
  for (const [platform, version] of Object.entries(versions)) {
    fs.writeFileSync(path.join(root, 'versions', platform), `${version}\n`);
  }
  fs.writeFileSync(
    path.join(root, 'apps', 'fnos', 'package', 'manifest'),
    `appname="flux-reader"\nversion="${manifestVersion}"\n`
  );
  fs.writeFileSync(
    path.join(root, 'apps', 'windows', 'src-tauri', 'Cargo.toml'),
    `[package]\nname = "flux-reader-windows"\nversion = "${windowsCargoVersion}"\n\n[dependencies]\nserde = "1"\n`
  );
  fs.writeFileSync(
    path.join(root, 'apps', 'windows', 'src-tauri', 'Cargo.lock'),
    `# Generated by Cargo.\nversion = 3\n\n[[package]]\nname = "flux-reader-windows"\nversion = "${windowsCargoLockVersion}"\n`
  );
  fs.writeFileSync(
    path.join(root, 'apps', 'windows', 'src-tauri', 'tauri.conf.json'),
    `${JSON.stringify({ productName: 'Flux Reader', version: tauriVersion }, null, 2)}\n`
  );
  fs.writeFileSync(
    path.join(root, 'apps', 'macos', 'FluxReader.xcodeproj', 'project.pbxproj'),
    [
      'Debug = {',
      `  MARKETING_VERSION = ${xcodeVersion};`,
      '};',
      'Release = {',
      `  MARKETING_VERSION = ${xcodeVersion};`,
      '};',
      '',
    ].join('\n')
  );
  return root;
}

afterEach(() => {
  while (temporaryRoots.length > 0) {
    const root = temporaryRoots.pop();
    const expectedPrefix = path.join(os.tmpdir(), 'flux-reader-version-test-');
    assert.ok(root.startsWith(expectedPrefix), `拒绝清理非测试目录：${root}`);
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test('validates independent platform versions', () => {
  const root = fixture();
  assert.deepEqual(syncVersion({ root }), {
    fnos: '1.2.3',
    macos: '2.3.4',
    windows: '3.4.5',
  });
  assert.equal(syncVersion({ root, platform: 'macos' }), '2.3.4');
});

test('uses platform-prefixed immutable tags and one platform asset', () => {
  assert.deepEqual(releaseMetadata('fnos', '1.2.3'), {
    platform: 'fnos',
    version: '1.2.3',
    tag: 'fnos/v1.2.3',
    asset: 'flux-reader-1.2.3.fpk',
  });
  assert.deepEqual(releaseMetadata('macos', '2.3.4'), {
    platform: 'macos',
    version: '2.3.4',
    tag: 'macos/v2.3.4',
    asset: 'Flux-Reader-2.3.4-unnotarized-universal.dmg',
    signedAsset: 'Flux-Reader-2.3.4-universal.dmg',
  });
  assert.deepEqual(releaseMetadata('windows', '3.4.5'), {
    platform: 'windows',
    version: '3.4.5',
    tag: 'windows/v3.4.5',
    asset: 'flux-reader-3.4.5-windows-x64.exe',
  });
});

test('writes one selected platform contract to GitHub Actions outputs', () => {
  const outputRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'flux-reader-version-test-'));
  temporaryRoots.push(outputRoot);
  const outputPath = path.join(outputRoot, 'github-output');
  const scriptPath = path.resolve(__dirname, '..', 'sync-version.js');
  const version = readVersionSource(path.resolve(__dirname, '..', '..'), 'windows').version;

  execFileSync(
    process.execPath,
    [scriptPath, '--check', '--platform', 'windows', '--github-output'],
    { env: { ...process.env, GITHUB_OUTPUT: outputPath }, stdio: 'pipe' },
  );

  assert.deepEqual(
    Object.fromEntries(
      fs.readFileSync(outputPath, 'utf8').trim().split('\n').map((line) => line.split('=', 2)),
    ),
    {
      platform: 'windows',
      version,
      tag: `windows/v${version}`,
      asset: `flux-reader-${version}-windows-x64.exe`,
      signed_asset: '',
    },
  );
});

test('rejects drift only for selected platforms', () => {
  const root = fixture({ manifestVersion: '1.2.2', windowsCargoVersion: '3.4.4' });
  assert.equal(syncVersion({ root, platform: 'macos' }), '2.3.4');
  assert.throws(() => syncVersion({ root, platform: 'fnos' }), /fnos=1\.2\.2/);
  assert.throws(() => syncVersion({ root, platform: 'windows' }), /windows=3\.4\.4/);
});

test('writes only selected distribution versions and remains idempotent', () => {
  const root = fixture({
    manifestVersion: '1.0.0',
    xcodeVersion: '2.0.0',
    windowsCargoVersion: '3.0.0',
    windowsCargoLockVersion: '3.0.0',
    tauriVersion: '3.0.0',
  });

  assert.equal(syncVersion({ root, platform: 'fnos', write: true }), '1.2.3');
  assert.match(
    fs.readFileSync(path.join(root, 'apps/fnos/package/manifest'), 'utf8'),
    /version="1\.2\.3"/,
  );
  assert.throws(() => syncVersion({ root, platform: 'macos' }), /macos=2\.0\.0/);
  assert.throws(() => syncVersion({ root, platform: 'windows' }), /windows=3\.0\.0/);

  assert.deepEqual(syncVersion({ root, write: true }), {
    fnos: '1.2.3',
    macos: '2.3.4',
    windows: '3.4.5',
  });
  assert.deepEqual(syncVersion({ root, write: true }), {
    fnos: '1.2.3',
    macos: '2.3.4',
    windows: '3.4.5',
  });
});

test('rejects invalid version files, ambiguous fields, and unknown platforms', () => {
  const invalidRoot = fixture();
  fs.writeFileSync(path.join(invalidRoot, 'versions/fnos'), '1.2\n');
  assert.throws(
    () => syncVersion({ root: invalidRoot, platform: 'fnos' }),
    /单行三段纯数字版本号/,
  );

  const duplicateRoot = fixture();
  fs.appendFileSync(path.join(duplicateRoot, 'apps/fnos/package/manifest'), 'version="9.9.9"\n');
  assert.throws(() => syncVersion({ root: duplicateRoot }), /只能包含一个 version 字段/);

  const duplicateCargoRoot = fixture();
  fs.appendFileSync(
    path.join(duplicateCargoRoot, 'apps/windows/src-tauri/Cargo.lock'),
    '\n[[package]]\nname = "flux-reader-windows"\nversion = "9.9.9"\n',
  );
  assert.throws(
    () => syncVersion({ root: duplicateCargoRoot, platform: 'windows' }),
    /Cargo\.lock 必须且只能包含一个 flux-reader-windows 包/,
  );
  assert.throws(() => syncVersion({ root: fixture(), platform: 'linux' }), /未知平台/);
});
